### ISSUE TITLE
There is an issue with things being put in other categories than what thermodynamics intended. 

### ISSUE THREAD

**Issue by Chunnyluny** [emipa606/DThermodynamicsHotMeals#2]
https://discord.com/channels/680705672911913016/693732045100154910/1126766292699979788 

this is a rentry link to the mods I use. I hope it is not a conflict between mods with overwriting their food or recipe policies or even their storage categories. since thermodynamics is applied on food, consumable, drugs, medicines as well. https://rentry.co/hkhvb

- thermodynamics makes almost every consumable having temp whether it is based or food or not. we have already fixed the issue with the animal feed interfering with animal logic, where silage was counted as cold drink instead of animal feed. for storage filter. I'm wondering if deep storage filter or item category from LWM deep storage is interfering with the categories.

- in game you have the storage filter, the drug policy, food recipe filter idk if they are all the same. so, it can be confusing me whether it is in the correct storage category so also counted as food, drugs, cold drink or medical supplement.  

- the mods I think are affected by the thermodynamics meals are: vgp garden medicine, vanilla brewing expanded, LWM deep storage, medical supplements with social supplements as well. the utility supplements are put in the drugs/weapon category since they solve the filth and blight problems from the game which are not affected to be stored cold or consumed cold. 

- ice-cream/dessert from VGP garden gourmet and vanilla cooking expanded is considered recreational food, but that needs to be cold so that is category cold meals which is correct. 

- I think it is odd to defrost your contact lenses which are added by the social supplements mod, maybe it depends if the item is perishable. They should be put under manufactured: medicines --> drugs. instead of food  category --> cold drinks. 
![](https://cdn.discordapp.com/attachments/693732045100154910/1126642671595819018/image.png)

- It might be the problem of LWM deep storage mod. it has experimental options to choose which items can be put in specific storage building. but if it not well figured like you want to put stone chunks in the fridge the storage filter tab when you select the fridge, it will have no content. so, if you reset the building in experimental options, it will be reverted back to normal.

- VGP garden medicine is listed as compatible the antibiotics is put under manufactured --> medicine --> drugs, description
![](https://cdn.discordapp.com/attachments/693732045100154910/1126647364006969354/image.png)

- medical supplements these are listed under non-perishable the mod adds drug cabinet, and I think it is best if the medical supplements are stored in drug cabinet or the one with fridge function. doubting whether it needs to be put under manufactured --> drugs --> medicine or non-perishable. https://steamcommunity.com/sharedfiles/filedetails/?id=2195037369 
![](https://cdn.discordapp.com/attachments/693732045100154910/1126646844651470898/image.png)

- question some items are being put in more than 1 category, that could be a problem; the juice from vanilla brewing expanded is put in meal category and non-alcoholic drink. where I think the juice should be the non-alcoholic drinks or grouped together with lemonade from brewing expanded. 
-  to match them the garden sodas from VGP garden drinks need to be in non-alcoholic drinks as well. ![](https://cdn.discordapp.com/attachments/693732045100154910/1126650244092932256/image.png)
- the cocktails added by vanilla brewing expanded are put as meals, which I think can be better considered as cold drinks.

**Comment by emipa606** [comment]
The lenses should be fixed now. Regarding the categories, a lot of mods add/change those so not sure if its possible to force it into specifics. 
Are there any that are in the wrong category when used with no other mods?
